name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan workflow setiap hari pada tengah malam UTC
  workflow_dispatch: # Memungkinkan eksekusi manual dari GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Supabase JS
        run: npm install @supabase/supabase-js

      - name: Ping Supabase Database
        env:
          SUPABASE_URL: ${{ sb_publishable_JL5K5fbvwtBckmto_Nu_-A_9Y-AQTsb }}
          SUPABASE_KEY: ${{ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsY2NpaHhlZnlzb3FmbXJucWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzMyODQsImV4cCI6MjA3MjYwOTI4NH0.xd0yLzIt_sLRGl5KCJjW77oY4l6iiBEvVtnK69nhfBk }}
        run: |
          node -e "
            const { createClient } = require('@supabase/supabase-js');
            const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

            async function pingDatabase() {
              try {
                const { data, error } = await supabase
                  .from('nama_tabel_kecil_Anda')
                  .select('id')
                  .limit(1);

                if (error) {
                  throw error;
                }
                console.log('Successfully pinged the Supabase database!');
              } catch (e) {
                console.error('Error pinging Supabase:', e.message);
                process.exit(1);
              }
            }
            pingDatabase();
          "
